name: Kneeler Boot v3 Validation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-scad:
    runs-on: ubuntu-latest
    container:
      image: openscad/openscad:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Coupler
        run: |
          openscad -o check_upper.stl kneeler-boots-v3/kneeler-boot-coupler.scad \
          -D 'upper_boot_pla();'

      - name: Verify Kneeler Boot Insert
        run: |
          openscad -o check_pad.stl kneeler-boots-v3/kneeler-boot-insert.scad \
          -D 'floor_pad_tpu();'
      
      - name: Upload STLs
        uses: actions/upload-artifact@v4
        with:
           name: kneeler-boot3-v2
           path: |
             kneeler-boot-coupler.stl
             kneeler-boot-insert.stl
